### ISSUE TITLE
build bfc62f4 : crash after a few minutes

### ISSUE THREAD

**Issue by AirBeeSee** [Angelius007/hassio-ecoflow-cloud#10]
Hello, 

cette version provoque chez moi , après quelques minutes , systématiquement une erreur.

>   File "/usr/local/lib/python3.12/ssl.py", line 1180, in send
>     return self._sslobj.write(data)
>            ^^^^^^^^^^^^^^^^^^^^^^^^
> ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2406)

- lorsque cette erreur vient, plus rien ne se met a jour.

- si je reload l'intégration , cela refonctionne , puis , cette erreur revient.

- si je remet le build précédent. tout est bon.

- j'ai testé en public API et en "application" Api.

- L'erreur semble venir plus "vite" , si me m'amuse a appeler plusieurs fois d'affilée un switch par exemple. (beep on/off , usb enable ...)

(Delta 2 Max + Batt Slave + PowerStream)

**Comment by Angelius007** [comment]
Sur cette version, deux changements :
- keepalive toutes les 10 secondes au lieu de 30 secondes.
- loop_start lancé uniquement si la connexion est OK
A voir si la fréquence augmentée du keepalive n'est pas la cause.

Je ne reproduits pas chez moi pour le moment (et pourtant je modifie pas mal les paramètres et j'ai des scénarios qui mettre à jour la charge en entrée de la batterie delta 2 max tout au long de la journée sans crash.

**Comment by AirBeeSee** [comment]
C'est ce que j'ai vu. Il n'y pas beaucoup de changement.
Du coup , j'ai fait du try and catch ...lol ..
Au final , il faut juste que je remette la ligne self.__client.loop_start() en ligne 46 après le reconnect.

Avec ta version , des le depart, par exemple , je vai sur la delta 2, je met le beeper sur "On", puis je bascule la sortie usb quelques fois .. et boum. ... crash. 

et en gros , j'ai quelque chose qui deconne avec mqtt qui n'arrive peut être pas chez toi et donc tu n'as pas le reconnect qui se met en route.

> 2024-08-18 21:00:12.785 ERROR (Thread-17 (_thread_main)) [custom_components.ecoflow_cloud.api.ecoflow_mqtt] Unexpected MQTT disconnection: 7 (Error count 19). Will auto-reconnect

**Comment by Angelius007** [comment]
oui, je viens de reproduire. En cas de reconnecte, la loop est coupée sans être relancée...

**Comment by Angelius007** [comment]
Pris en compte sur le merge : 
https://github.com/Angelius007/hassio-ecoflow-cloud/pull/11
