### ISSUE TITLE
Power Stream custom Load is incorrect 

### ISSUE THREAD

**Issue by jmgfr** [Angelius007/hassio-ecoflow-cloud#7]
French :
Merci pour l'ajout des commandes et paramètrage du powerStream :-)
L'utilisation de la class "ChargingPowerEntity" entraine un bug, cette valeur étant en deciWatt sur l'api ecoflow
Le curseur indique donc une valeur 10 foix plus élevée que le règlage réel, et modifié le curseur modifie avec une valeur 10x plus faible en réel dans le power stream
Règlage HA à 600W -> le power Stream envoie 60W sur le réseau
Règlage à 80 W depuis l'appli Ecoflow, HA affiche 800W
Je pense qu'il faudrait créer une classe DeciChargingPowerEntity

English :
Thanks for adding the commands and powerStream settings :-)
Using "ChargingPowerEntity" class causes a bug, this value being in deciWatt on the ecoflow api
The cursor therefore indicates a value 10 times higher than the actual setting, and modified the cursor with a value 10x lower in real life in the power stream
HA setting at 600W -> the power Stream sends 60W to the network
Setting to 80 W from the Ecoflow app, HA displays 800W
I think we should create a DeciChargingPowerEntity class

**Comment by Angelius007** [comment]
Bien vu !
Reproduit et corrigé. Je pousse la modif tout à l'heure

**Comment by Angelius007** [comment]
Snif, c'est finalement pas aussi simple.
En / par 10 pour la restitution (comme pour les sensors), ça entraine un comportement similaire en utilisant le sélecteur via l'ihm. (si je choisis 70 sur le sélecteur, ça le transforme en 7 en restitution donc assez perturbant aussi).
Je vois si je trouve une autre solution

**Comment by AirBeeSee** [comment]
peut être , en attendant , "tricher" dans l'envoi de la commande  WN511_SET_PERMANENT_WATTS_PACK en altérant la valeur avant l'envoi.

**Comment by jmgfr** [comment]
Ce n'est effectivement pas simple. 
Il serait possible de multiplier la valeur par 10 avant envoi, Mais il faudrait aussi diviser par 10 la valeur reçue pour un affichage correct 
Pour ma part j'ai installé Home assistant cette semaine pour cette intégration après 10 ans sous jeedom et n'ai pas encore regardé les "class" Ha utilisées ni les surcharges possible. 
Il y a du boulot pour être sûr que ce soit "user friendly" et utilisable par tous. 
Sinon, si ce n'est que pour moi, je multiplierais tout par 10.
Un "slicer" qui va jusqu'à 8000 (pour 800 Watts) et je m'adapte.

**Comment by Angelius007** [comment]
https://developer-eu.ecoflow.com/us/document/powerStreamMicroInverter
Le truc, c'est que la valeur est bien exprimée en 0.1W et pas en W. Donc le comportement est cohérent avec la documentation.
Donc on reçoit effectivement une valeur x10 avec une unité exprimée en W au lieu de 0.1W mais il faut aussi communiquer avec le Powerstream en 0.1W, il faut s'assurer que l'ensemble reste cohérent. Et la gestion du curseur est aussi impactée par la division. Idéalement, il aurait fallu que homeassistant accepte les déciWatt avec une conversion auto à l'affichage en W mais ce n'est pas le cas aujourd'hui : 
`
# Power units
class UnitOfPower(StrEnum):
    """Power units."""

    WATT = "W"
    KILO_WATT = "kW"
    BTU_PER_HOUR = "BTU/h"
`

=> Donc il faut uniquement impacter l'affichage sur une élément de type Sensor, c'est simple car il n'y a que de l'affichage. Pour des curseurs, cela oblige à bidouiller dans tous les sens pour avoir une cohérence globale (mais tout est possible en informatique :) )

**Comment by AirBeeSee** [comment]
Pour le moment , je bascule le max sur 8000 dans ChargingPowerEntity.
PS: par contre , comme je l'ai indiqué dans une issue, cette version crash.
J'ai du remettre la version precendente de ecoflow_mqtt.Py dans Api
